name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push backend image
      - name: Build and push backend
        run: |
          docker build -t praveenlichchavi/sms-backend:latest ./smsbackend/smsbackend
          docker push praveenlichchavi/sms-backend:latest

      # Build and push frontend image
      - name: Build and push frontend
        run: |
          docker build -t praveenlichchavi/sms-frontend:latest ./sms
          docker push praveenlichchavi/sms-frontend:latest

      # Build and push nginx image
      - name: Build and push nginx
        run: |
          docker build -t praveenlichchavi/sms-nginx:latest ./nginx
          docker push praveenlichchavi/sms-nginx:latest

      # Deploy to EC2
      - name: Deploy to EC2
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          echo "$EC2_SSH_KEY" > key.pem
          chmod 400 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem ${EC2_USER}@${EC2_HOST} << 'EOF'
            # Commands to run on EC2
            sudo mkdir -p /home/ubuntu/app
            sudo chown ubuntu:ubuntu /home/ubuntu/app
            cd /home/ubuntu/app
            echo "version: '3'" > docker-compose.yml
            echo "$(cat ${{ github.workspace }}/docker-compose.yml)" >> docker-compose.yml
            docker-compose down
            docker-compose pull
            docker-compose up -d
          EOF